language: python
python:
  - "2.7"
cache: apt

env:
  - TRANSLATE=true
  - TESTDIR=testing/
  - TESTDIR=test_phpt/[^e]*/
  - TESTDIR="test_phpt/ext/ -k 'not standard'"
  - TESTDIR=test_phpt/ext/standard/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmysqlclient-dev
  - sudo apt-get install -y libpcre3-dev
  - sudo apt-get install -y librhash-dev
  - sudo apt-get install -y libbz2-dev
  - sudo apt-get install -y php5-cli
  - "sudo sed -i 's/# fr_FR ISO-8859-1/fr_FR ISO-8859-1/' /etc/locale.gen"
  - sudo locale-gen

install:
  - wget https://bitbucket.org/pypy/pypy/get/default.tar.gz
  - mkdir pypy && tar xf default.tar.gz -C pypy --strip-components 1
  - pip install -r requirements.txt

script:
  - ./travis.sh

notifications:
  irc:
    channels: "irc.freenode.org#hippyvm"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
